import { PrismaClient } from '../../src/generated/prisma/client'

export async function seedProductos(prisma: PrismaClient) {

    const proveedores = await prisma.proveedores.findMany()
    const categorias = await prisma.categorias.findMany()

    const miniso = proveedores.find((p: any) => p.nombre_negocio === 'Miniso Bolivia')!
    const giftland = proveedores.find((p: any) => p.nombre_negocio === 'Giftland Bolivia')!
    const missFlores = proveedores.find((p: any) => p.nombre_negocio === 'Miss Flores')!
    const arteFloral = proveedores.find((p: any) => p.nombre_negocio === 'Arte Floral Bolivia')!
    const wonder = proveedores.find((p: any) => p.nombre_negocio === 'Wonder Perfumes Bolivia')!

    const catPeluches = categorias.find((c: any) => c.nombre === 'Peluches')!
    const catJuguetes = categorias.find((c: any) => c.nombre === 'Juguetes')!
    const catSaludBelleza = categorias.find((c: any) => c.nombre === 'Salud y Belleza')!
    const catTecnologia = categorias.find((c: any) => c.nombre === 'Tecnología')!
    const catAccesorios = categorias.find((c: any) => c.nombre === 'Accesorios y Bisutería')!
    const catFlores = categorias.find((c: any) => c.nombre === 'Flores')!
    const catPerfumes = categorias.find((c: any) => c.nombre === 'Perfumes')!
    const catSorpresas = categorias.find((c: any) => c.nombre === 'Sorpresas')!

    await prisma.productos.createMany({
        skipDuplicates: true,
        data: [
            // ============= MINISO - PELUCHES =============
            {
                proveedor_id: miniso.id,
                categoria_id: catPeluches.id,
                nombre: 'Christmas Tree Pillow',
                descripcion: 'Almohada decorativa con diseño de árbol de Navidad, suave y acogedora',
                precio_base: 79.00,
                precio_venta: 95.00,
                stock: 10,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234682/Christmas_Tree_Pillow_psunwx.png',
                ocasiones: ['navidad', 'cumpleaños'],
                personalidades: ['detallista', 'romántico'],
                genero_destinatario: 'cualquiera',
                edad_min: 3,
                edad_max: 99,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: miniso.id,
                categoria_id: catPeluches.id,
                nombre: 'Christmas Tree Pig Plush Toy',
                descripcion: 'Peluche de cerdito con diseño de árbol de Navidad, material suave',
                precio_base: 179.00,
                precio_venta: 215.00,
                stock: 5,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234683/Christmas_Tree_Pig_Plush_Toy_zyxvsw.webp',
                ocasiones: ['navidad', 'cumpleaños'],
                personalidades: ['divertido', 'detallista'],
                genero_destinatario: 'cualquiera',
                edad_min: 3,
                edad_max: 99,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: miniso.id,
                categoria_id: catPeluches.id,
                nombre: 'Penguin Plush Toy',
                descripcion: 'Peluche de pingüino súper suave, perfecto para regalar',
                precio_base: 59.00,
                precio_venta: 71.00,
                stock: 6,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234695/Penguin_Plush_Toy_ujv8qp.jpg',
                ocasiones: ['cumpleaños', 'día del niño'],
                personalidades: ['divertido', 'cariñoso'],
                genero_destinatario: 'cualquiera',
                edad_min: 3,
                edad_max: 99,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: miniso.id,
                categoria_id: catPeluches.id,
                nombre: 'Peluche de animal disfrazado de Stitch de Disney',
                descripcion: 'Peluche oficial de Stitch de Disney disfrazado de animal',
                precio_base: 169.00,
                precio_venta: 203.00,
                stock: 2,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234699/Peluche_de_animal_disfrazado_de_Stitch_de_Disney_ma0gw4.jpg',
                ocasiones: ['cumpleaños', 'día del niño'],
                personalidades: ['divertido', 'fanático'],
                genero_destinatario: 'cualquiera',
                edad_min: 5,
                edad_max: 99,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: miniso.id,
                categoria_id: catPeluches.id,
                nombre: 'Peluche de Harry Potter (Hermione)',
                descripcion: 'Peluche oficial de Hermione Granger de Harry Potter',
                precio_base: 179.00,
                precio_venta: 215.00,
                stock: 16,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234697/Peluche_de_Harry_Potter_Hermione_l2p18h.jpg',
                ocasiones: ['cumpleaños', 'graduación'],
                personalidades: ['fanático', 'nerd'],
                genero_destinatario: 'cualquiera',
                edad_min: 8,
                edad_max: 99,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: miniso.id,
                categoria_id: catPeluches.id,
                nombre: 'Peluche de cordero Sakura de la serie Baa',
                descripcion: 'Peluche de cordero color Sakura, diseño kawaii japonés',
                precio_base: 109.00,
                precio_venta: 131.00,
                stock: 20,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234693/Peluche_de_cordero_Sakura_de_la_serie_Baa_q9vwu5.jpg',
                ocasiones: ['cumpleaños', 'amistad'],
                personalidades: ['kawaii', 'detallista'],
                genero_destinatario: 'cualquiera',
                edad_min: 3,
                edad_max: 99,
                permite_mensaje: true,
                permite_empaque: true,
            },

            // ============= MINISO - JUGUETES =============
            {
                proveedor_id: miniso.id,
                categoria_id: catJuguetes.id,
                nombre: 'Rompecabezas de animales en 3D',
                descripcion: 'Rompecabezas 3D de animales, fomenta la creatividad',
                precio_base: 59.00,
                precio_venta: 71.00,
                stock: 10,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234670/Rompecabezas_de_animales_en_3D_msxkjv.jpg',
                ocasiones: ['cumpleaños', 'día del niño'],
                personalidades: ['creativo', 'inteligente'],
                genero_destinatario: 'cualquiera',
                edad_min: 6,
                edad_max: 16,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: miniso.id,
                categoria_id: catJuguetes.id,
                nombre: 'Huevo sorpresa de cochecitos de aleación',
                descripcion: 'Huevo sorpresa con cochecitos de aleación, 7 modelos diferentes',
                precio_base: 29.00,
                precio_venta: 35.00,
                stock: 5,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234688/Huevo_sorpresa_de_cochecitos_de_aleaci%C3%B3n_omtoon.jpg',
                ocasiones: ['cumpleaños', 'día del niño'],
                personalidades: ['aventurero', 'divertido'],
                genero_destinatario: 'niño',
                edad_min: 4,
                edad_max: 12,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: miniso.id,
                categoria_id: catJuguetes.id,
                nombre: 'Juego de mesa Bean Eater',
                descripcion: 'Juego de mesa divertido Bean Eater para jugar en familia',
                precio_base: 89.00,
                precio_venta: 107.00,
                stock: 6,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234690/Juego_de_mesa_Bean_Eater_kvkgfg.jpg',
                ocasiones: ['cumpleaños', 'navidad'],
                personalidades: ['divertido', 'social'],
                genero_destinatario: 'cualquiera',
                edad_min: 8,
                edad_max: 99,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: miniso.id,
                categoria_id: catJuguetes.id,
                nombre: 'Bloques de construcción de campanilla',
                descripcion: 'Bloques de construcción temática de Campanilla',
                precio_base: 49.00,
                precio_venta: 59.00,
                stock: 2,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234679/Bloques_de_construcci%C3%B3n_de_campanilla_buutpq.jpg',
                ocasiones: ['cumpleaños', 'día del niño'],
                personalidades: ['creativo', 'imaginativo'],
                genero_destinatario: 'niña',
                edad_min: 4,
                edad_max: 12,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: miniso.id,
                categoria_id: catJuguetes.id,
                nombre: 'Bolígrafo de caja sorpresa con varita de Harry Potter',
                descripcion: 'Bolígrafo sorpresa dentro de caja con diseño de varita de Harry Potter',
                precio_base: 49.00,
                precio_venta: 59.00,
                stock: 16,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234675/Bol%C3%ADgrafo_de_caja_sorpresa_con_varita_de_Harry_Potter_ia0iog.jpg',
                ocasiones: ['cumpleaños', 'vuelta a clases'],
                personalidades: ['fanático', 'nerd'],
                genero_destinatario: 'cualquiera',
                edad_min: 8,
                edad_max: 99,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: miniso.id,
                categoria_id: catJuguetes.id,
                nombre: 'Rompecabezas 3D de la colección My Little Pony',
                descripcion: 'Rompecabezas 3D de My Little Pony, armable y divertido',
                precio_base: 69.00,
                precio_venta: 83.00,
                stock: 20,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234697/Rompecabezas_3D_de_la_colecci%C3%B3n_My_Little_Pony_idrnpn.jpg',
                ocasiones: ['cumpleaños', 'día del niño'],
                personalidades: ['creativo', 'divertido'],
                genero_destinatario: 'niña',
                edad_min: 5,
                edad_max: 14,
                permite_mensaje: true,
                permite_empaque: true,
            },

            // ============= MINISO - SALUD Y BELLEZA =============
            {
                proveedor_id: miniso.id,
                categoria_id: catSaludBelleza.id,
                nombre: 'Espejo de mano de la colección Barbie',
                descripcion: 'Espejo de mano con diseño de Barbie, colección oficial',
                precio_base: 59.00,
                precio_venta: 71.00,
                stock: 10,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234686/Espejo_de_mano_de_la_colecci%C3%B3n_Barbie_wreykj.jpg',
                ocasiones: ['cumpleaños', 'día de la madre'],
                personalidades: ['detallista', 'fashion'],
                genero_destinatario: 'mujer',
                edad_min: 12,
                edad_max: 99,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: miniso.id,
                categoria_id: catSaludBelleza.id,
                nombre: 'Antifaz de peluche para dormir de la colección Happy Foods',
                descripcion: 'Antifaz de peluche para dormir, diseño Happy Foods',
                precio_base: 39.00,
                precio_venta: 47.00,
                stock: 5,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234677/Antifaz_de_peluche_para_dormir_de_la_colecci%C3%B3n_Happy_Foods_up8szc.jpg',
                ocasiones: ['cumpleaños', 'viaje'],
                personalidades: ['relajado', 'detallista'],
                genero_destinatario: 'cualquiera',
                edad_min: 15,
                edad_max: 99,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: miniso.id,
                categoria_id: catSaludBelleza.id,
                nombre: 'Espejo portátil brillante de la colección Ilusion',
                descripcion: 'Espejo portátil con acabado brillante, diseño elegante',
                precio_base: 29.00,
                precio_venta: 35.00,
                stock: 6,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234687/Espejo_port%C3%A1til_brillante_de_la_colecci%C3%B3n_Ilusion_htnr9j.jpg',
                ocasiones: ['cumpleaños', 'día de la madre'],
                personalidades: ['fashion', 'detallista'],
                genero_destinatario: 'mujer',
                edad_min: 12,
                edad_max: 99,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: miniso.id,
                categoria_id: catSaludBelleza.id,
                nombre: 'Juego de recipientes portátiles para mezclar mascarillas faciales',
                descripcion: 'Set de recipientes portátiles para mezclar mascarillas faciales con tapa',
                precio_base: 29.00,
                precio_venta: 35.00,
                stock: 2,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234691/Juego_de_recipientes_port%C3%A1tiles_para_mezclar_mascarillas_faciales_con_tapa_nabyac.jpg',
                ocasiones: ['cumpleaños', 'spa day'],
                personalidades: ['detallista', 'practico'],
                genero_destinatario: 'mujer',
                edad_min: 18,
                edad_max: 99,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: miniso.id,
                categoria_id: catSaludBelleza.id,
                nombre: 'Mini espejo con cepillo de la colección Barbie',
                descripcion: 'Mini espejo con cepillo incluido, diseño Barbie',
                precio_base: 39.00,
                precio_venta: 47.00,
                stock: 16,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234694/Mini_espejo_con_cepillo_de_la_colecci%C3%B3n_Barbie_bmd1if.jpg',
                ocasiones: ['cumpleaños', 'día de la madre'],
                personalidades: ['fashion', 'practico'],
                genero_destinatario: 'mujer',
                edad_min: 8,
                edad_max: 99,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: miniso.id,
                categoria_id: catSaludBelleza.id,
                nombre: 'Llavero con espejo en forma de corazón de la colección MIKKO',
                descripcion: 'Llavero funcional con espejo en forma de corazón',
                precio_base: 39.00,
                precio_venta: 47.00,
                stock: 20,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777235689/Llavero_con_espejo_en_forma_de_coraz%C3%B3n_de_la_colecci%C3%B3n_MIKKO_ox79xq.jpg',
                ocasiones: ['cumpleaños', 'aniversario'],
                personalidades: ['romántico', 'practico'],
                genero_destinatario: 'mujer',
                edad_min: 12,
                edad_max: 99,
                permite_mensaje: true,
                permite_empaque: true,
            },

            // ============= MINISO - TECNOLOGÍA =============
            {
                proveedor_id: miniso.id,
                categoria_id: catTecnologia.id,
                nombre: 'Auriculares de música coloridos',
                descripcion: 'Auriculares coloridos, diseño moderno',
                precio_base: 39.00,
                precio_venta: 47.00,
                stock: 10,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234679/Auriculares_de_m%C3%BAsica_coloridos_ghczpv.jpg',
                ocasiones: ['cumpleaños', 'graduación'],
                personalidades: ['tecnológico', 'divertido'],
                genero_destinatario: 'cualquiera',
                edad_min: 12,
                edad_max: 40,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: miniso.id,
                categoria_id: catTecnologia.id,
                nombre: 'Soporte para teléfono móvil de la colección Disney',
                descripcion: 'Soporte para celular con diseño de Disney',
                precio_base: 39.00,
                precio_venta: 47.00,
                stock: 5,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234671/Soporte_para_tel%C3%A9fono_m%C3%B3vil_de_la_colecci%C3%B3n_Disney_vulexz.webp',
                ocasiones: ['cumpleaños', 'tecnología'],
                personalidades: ['fanático', 'tecnológico'],
                genero_destinatario: 'cualquiera',
                edad_min: 12,
                edad_max: 50,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: miniso.id,
                categoria_id: catTecnologia.id,
                nombre: 'Bolso para ordenador con doble cremallera',
                descripcion: 'Bolso para laptop con doble cremallera, acolchado',
                precio_base: 149.00,
                precio_venta: 179.00,
                stock: 6,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234676/Bolso_para_ordenador_con_doble_cremallera_busmgv.webp',
                ocasiones: ['cumpleaños', 'graduación'],
                personalidades: ['practico', 'tecnológico'],
                genero_destinatario: 'cualquiera',
                edad_min: 18,
                edad_max: 50,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: miniso.id,
                categoria_id: catTecnologia.id,
                nombre: 'Alfombrilla de ratón redonda Toy Story (Hamm)',
                descripcion: 'Mousepad redondo con diseño de Hamm de Toy Story',
                precio_base: 29.00,
                precio_venta: 35.00,
                stock: 2,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234673/Alfombrilla_de_rat%C3%B3n_redonda_de_la_colecci%C3%B3n_Toy_Story_Hamm_jzultp.jpg',
                ocasiones: ['cumpleaños', 'tecnología'],
                personalidades: ['divertido', 'fanático'],
                genero_destinatario: 'cualquiera',
                edad_min: 10,
                edad_max: 40,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: miniso.id,
                categoria_id: catTecnologia.id,
                nombre: 'Teclado mini con cable de moda SW-KB611',
                descripcion: 'Teclado mini con cable, diseño moderno color pastel',
                precio_base: 89.00,
                precio_venta: 107.00,
                stock: 16,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234671/Teclado_mini_con_cable_de_moda_Modelo_SW-KB611_hiq2ed.jpg',
                ocasiones: ['cumpleaños', 'vuelta a clases'],
                personalidades: ['tecnológico', 'fashion'],
                genero_destinatario: 'cualquiera',
                edad_min: 14,
                edad_max: 40,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: miniso.id,
                categoria_id: catTecnologia.id,
                nombre: 'Auriculares plegables',
                descripcion: 'Auriculares plegables, diseño compacto, almohadillas suaves',
                precio_base: 119.00,
                precio_venta: 143.00,
                stock: 20,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234681/Auriculares_plegables_gci8pk.jpg',
                ocasiones: ['cumpleaños', 'viaje'],
                personalidades: ['tecnológico', 'practico'],
                genero_destinatario: 'cualquiera',
                edad_min: 12,
                edad_max: 50,
                permite_mensaje: true,
                permite_empaque: true,
            },

            // ============= MINISO - ACCESORIOS =============
            {
                proveedor_id: miniso.id,
                categoria_id: catAccesorios.id,
                nombre: 'Banda elástica-BM51',
                descripcion: 'Banda elástica para cabello, diseño moderno',
                precio_base: 29.00,
                precio_venta: 35.00,
                stock: 10,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234674/banda_el%C3%A1stica-BM51_fgpeip.jpg',
                ocasiones: ['cumpleaños', 'día de la madre'],
                personalidades: ['practico', 'fashion'],
                genero_destinatario: 'mujer',
                edad_min: 8,
                edad_max: 60,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: miniso.id,
                categoria_id: catAccesorios.id,
                nombre: 'Diadema fina de acrílico-BM32',
                descripcion: 'Diadema fina de acrílico, diseño elegante',
                precio_base: 39.00,
                precio_venta: 47.00,
                stock: 5,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234685/Diadema_fina_de_acr%C3%ADlico-BM32_phtson.jpg',
                ocasiones: ['cumpleaños', 'día de la madre'],
                personalidades: ['fashion', 'elegante'],
                genero_destinatario: 'mujer',
                edad_min: 10,
                edad_max: 60,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: miniso.id,
                categoria_id: catAccesorios.id,
                nombre: 'Abrazadera de aleación-BM29',
                descripcion: 'Abrazadera para cabello hecha de aleación',
                precio_base: 29.00,
                precio_venta: 35.00,
                stock: 6,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234672/Abrazadera_de_aleaci%C3%B3n-BM29_lzd5xo.jpg',
                ocasiones: ['cumpleaños', 'día de la madre'],
                personalidades: ['practico', 'fashion'],
                genero_destinatario: 'mujer',
                edad_min: 12,
                edad_max: 60,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: miniso.id,
                categoria_id: catAccesorios.id,
                nombre: 'Llavero de aleación-BM90',
                descripcion: 'Llavero de aleación de alta calidad',
                precio_base: 39.00,
                precio_venta: 47.00,
                stock: 2,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234692/Llavero_de_aleaci%C3%B3n-BM90_hyxsbq.jpg',
                ocasiones: ['cumpleaños', 'amistad'],
                personalidades: ['practico', 'detallista'],
                genero_destinatario: 'cualquiera',
                edad_min: 10,
                edad_max: 70,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: miniso.id,
                categoria_id: catAccesorios.id,
                nombre: 'Juego de cadena de aleación-BM23',
                descripcion: 'Juego de cadena de aleación, set completo',
                precio_base: 119.00,
                precio_venta: 143.00,
                stock: 16,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234689/Juego_de_cadena_de_aleaci%C3%B3n-BM23_icmskv.jpg',
                ocasiones: ['cumpleaños', 'aniversario'],
                personalidades: ['elegante', 'detallista'],
                genero_destinatario: 'mujer',
                edad_min: 15,
                edad_max: 60,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: miniso.id,
                categoria_id: catAccesorios.id,
                nombre: 'Clip de cruz con letras-BM31',
                descripcion: 'Clip de cruz con letras personalizables',
                precio_base: 59.00,
                precio_venta: 71.00,
                stock: 20,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234684/Clip_de_cruz_con_letras-BM31_ajwgf6.jpg',
                ocasiones: ['cumpleaños', 'religión'],
                personalidades: ['detallista', 'religioso'],
                genero_destinatario: 'cualquiera',
                edad_min: 12,
                edad_max: 70,
                permite_mensaje: true,
                permite_empaque: true,
            },

            // ============= GIFTLAND - PELUCHES =============
            {
                proveedor_id: giftland.id,
                categoria_id: catPeluches.id,
                nombre: 'Five Nights at Freddys',
                descripcion: 'Peluche oficial de Five Nights at Freddys, colección exclusiva',
                precio_base: 100.00,
                precio_venta: 120.00,
                stock: 10,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234746/Five_Nights_at_Freddy_s_zucids.jpg',
                ocasiones: ['cumpleaños', 'día del niño'],
                personalidades: ['divertido', 'fanático'],
                genero_destinatario: 'cualquiera',
                edad_min: 8,
                edad_max: 35,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: giftland.id,
                categoria_id: catPeluches.id,
                nombre: 'Cojín Nick y Judy Zootopia',
                descripcion: 'Cojín suave de Nick y Judy de Zootopia, ideal para decoración',
                precio_base: 120.00,
                precio_venta: 144.00,
                stock: 5,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234755/Cojin_Nick_y_Judy_Zootopia_ytsbso.jpg',
                ocasiones: ['cumpleaños', 'día del niño'],
                personalidades: ['divertido', 'detallista'],
                genero_destinatario: 'cualquiera',
                edad_min: 6,
                edad_max: 40,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: giftland.id,
                categoria_id: catPeluches.id,
                nombre: 'Baby Cry de Blind Box',
                descripcion: 'Peluche Baby Cry de Blind Box, edición limitada',
                precio_base: 110.00,
                precio_venta: 132.00,
                stock: 6,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234752/Baby_Cry_de_Blind_Box_vofpmx.jpg',
                ocasiones: ['cumpleaños', 'coleccionistas'],
                personalidades: ['divertido', 'detallista'],
                genero_destinatario: 'cualquiera',
                edad_min: 8,
                edad_max: 40,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: giftland.id,
                categoria_id: catPeluches.id,
                nombre: 'Stitch que respira',
                descripcion: 'Peluche de Stitch con movimiento que simula respiración',
                precio_base: 140.00,
                precio_venta: 168.00,
                stock: 2,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234761/Stitch_que_respira_gvacro.jpg',
                ocasiones: ['cumpleaños', 'día del niño'],
                personalidades: ['divertido', 'relajante'],
                genero_destinatario: 'cualquiera',
                edad_min: 5,
                edad_max: 40,
                permite_mensaje: true,
                permite_empaque: true,
            },

            // ============= GIFTLAND - JUGUETES =============
            {
                proveedor_id: giftland.id,
                categoria_id: catJuguetes.id,
                nombre: 'Box Zootopia Disney',
                descripcion: 'Caja sorpresa de Zootopia Disney con múltiples accesorios',
                precio_base: 110.00,
                precio_venta: 132.00,
                stock: 16,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234747/Box_Zootopia_Disney_ikjjhz.jpg',
                ocasiones: ['cumpleaños', 'día del niño'],
                personalidades: ['divertido', 'aventurero'],
                genero_destinatario: 'cualquiera',
                edad_min: 5,
                edad_max: 14,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: giftland.id,
                categoria_id: catJuguetes.id,
                nombre: 'Lámparas Silicona (Recargable)',
                descripcion: 'Lámpara de silicona recargable, suave y decorativa',
                precio_base: 160.00,
                precio_venta: 192.00,
                stock: 20,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234751/L%C3%A1mparas_Silicona_Recargable_ijibji.jpg',
                ocasiones: ['cumpleaños', 'navidad'],
                personalidades: ['detallista', 'relajante'],
                genero_destinatario: 'cualquiera',
                edad_min: 5,
                edad_max: 60,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: giftland.id,
                categoria_id: catJuguetes.id,
                nombre: 'Mario Cars',
                descripcion: 'Juguete de Mario Cars, colección oficial de Nintendo',
                precio_base: 60.00,
                precio_venta: 72.00,
                stock: 10,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234748/Mario_Cars_ujkmih.jpg',
                ocasiones: ['cumpleaños', 'día del niño'],
                personalidades: ['divertido', 'fanático'],
                genero_destinatario: 'cualquiera',
                edad_min: 4,
                edad_max: 14,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: giftland.id,
                categoria_id: catJuguetes.id,
                nombre: 'Naturo Blind box',
                descripcion: 'Blind box de Naruto, colección sorpresa de personajes',
                precio_base: 140.00,
                precio_venta: 168.00,
                stock: 5,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234760/Naturo_Blind_box_iskbk3.jpg',
                ocasiones: ['cumpleaños', 'coleccionistas'],
                personalidades: ['fanático', 'aventurero'],
                genero_destinatario: 'cualquiera',
                edad_min: 12,
                edad_max: 40,
                permite_mensaje: true,
                permite_empaque: true,
            },

            // ============= GIFTLAND - SORPRESAS CIEGAS =============
            {
                proveedor_id: giftland.id,
                categoria_id: catSorpresas.id,
                nombre: 'Arreglos Huntrix',
                descripcion: 'Arreglo sorpresa Huntrix, caja misteriosa con sorpresas',
                precio_base: 135.00,
                precio_venta: 162.00,
                stock: 6,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234757/Arreglos_Huntrix_ieis29.jpg',
                ocasiones: ['cumpleaños', 'sorpresa'],
                personalidades: ['aventurero', 'divertido'],
                genero_destinatario: 'cualquiera',
                edad_min: 8,
                edad_max: 50,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: giftland.id,
                categoria_id: catSorpresas.id,
                nombre: 'Box Mario Bross',
                descripcion: 'Caja sorpresa de Mario Bross, múltiples personajes y accesorios',
                precio_base: 125.00,
                precio_venta: 150.00,
                stock: 2,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234759/Box_Mario_Bross_zp2kzm.jpg',
                ocasiones: ['cumpleaños', 'día del niño'],
                personalidades: ['divertido', 'fanático'],
                genero_destinatario: 'cualquiera',
                edad_min: 5,
                edad_max: 40,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: giftland.id,
                categoria_id: catSorpresas.id,
                nombre: 'Tutsi pop',
                descripcion: 'Tutsi pop, juguete sensorial antiestrés',
                precio_base: 85.00,
                precio_venta: 102.00,
                stock: 16,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234763/Tutsi_pop_ot0eig.jpg',
                ocasiones: ['cumpleaños', 'antiestrés'],
                personalidades: ['relajante', 'divertido'],
                genero_destinatario: 'cualquiera',
                edad_min: 5,
                edad_max: 60,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: giftland.id,
                categoria_id: catSorpresas.id,
                nombre: 'Helados gigantes',
                descripcion: 'Helados gigantes decorativos, ideales para regalar',
                precio_base: 90.00,
                precio_venta: 108.00,
                stock: 20,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234757/Helados_gigantes_pzv4hb.jpg',
                ocasiones: ['cumpleaños', 'verano'],
                personalidades: ['divertido', 'detallista'],
                genero_destinatario: 'cualquiera',
                edad_min: 5,
                edad_max: 50,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: giftland.id,
                categoria_id: catSorpresas.id,
                nombre: 'Box Hotwheels',
                descripcion: 'Caja sorpresa de Hotwheels, múltiples carritos',
                precio_base: 98.00,
                precio_venta: 118.00,
                stock: 10,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234750/Box_Hotwheels_jjeldt.jpg',
                ocasiones: ['cumpleaños', 'día del niño'],
                personalidades: ['aventurero', 'divertido'],
                genero_destinatario: 'niño',
                edad_min: 4,
                edad_max: 14,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: giftland.id,
                categoria_id: catSorpresas.id,
                nombre: 'Box Mario Princesas',
                descripcion: 'Caja sorpresa de Mario Princesas, colección especial',
                precio_base: 125.00,
                precio_venta: 150.00,
                stock: 5,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234755/Box_Mario_Princesas_fpbl3s.jpg',
                ocasiones: ['cumpleaños', 'día del niño'],
                personalidades: ['divertido', 'fanático'],
                genero_destinatario: 'niña',
                edad_min: 5,
                edad_max: 14,
                permite_mensaje: true,
                permite_empaque: true,
            },

            // ============= MISS FLORES =============
            {
                proveedor_id: missFlores.id,
                categoria_id: catFlores.id,
                nombre: 'Ramo grande 100 Rosas Rojas',
                descripcion: 'Ramo espectacular de 100 rosas rojas frescas, ideal para aniversarios y propuestas',
                precio_base: 1150.00,
                precio_venta: 1150.00,
                stock: 6,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234717/Ramo_grande_100_Rosas_Rojas_cvkwlp.webp',
                ocasiones: ['aniversario', 'propuesta', 'san valentín'],
                personalidades: ['romántico', 'detallista'],
                genero_destinatario: 'mujer',
                edad_min: 18,
                edad_max: 80,
                permite_mensaje: true,
                permite_empaque: false,
            },
            {
                proveedor_id: missFlores.id,
                categoria_id: catFlores.id,
                nombre: 'Arreglo Nelly',
                descripcion: 'Arreglo floral elegante, combinación de flores frescas',
                precio_base: 220.00,
                precio_venta: 220.00,
                stock: 2,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234720/Arreglo_Nelly_rxwlq5.webp',
                ocasiones: ['cumpleaños', 'agradecimiento'],
                personalidades: ['detallista', 'elegante'],
                genero_destinatario: 'mujer',
                edad_min: 18,
                edad_max: 70,
                permite_mensaje: true,
                permite_empaque: false,
            },
            {
                proveedor_id: missFlores.id,
                categoria_id: catFlores.id,
                nombre: 'La Maceta Serenidad Clásica',
                descripcion: 'Maceta decorativa con planta, ideal para regalar en cualquier ocasión',
                precio_base: 50.00,
                precio_venta: 50.00,
                stock: 16,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234719/La_Maceta_Serenidad_Cl%C3%A1sica_q89kwx.webp',
                ocasiones: ['cumpleaños', 'inauguración'],
                personalidades: ['relajado', 'detallista'],
                genero_destinatario: 'cualquiera',
                edad_min: 15,
                edad_max: 80,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: missFlores.id,
                categoria_id: catFlores.id,
                nombre: 'MINI BOUQUET GRACIAS MAMA',
                descripcion: 'Mini ramo especial para mamá, con dedicatoria incluida',
                precio_base: 220.00,
                precio_venta: 220.00,
                stock: 20,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234719/MINI_BOUQUET_GRACIAS_MAMA_nnnrmg.webp',
                ocasiones: ['día de la madre', 'cumpleaños'],
                personalidades: ['romántico', 'detallista'],
                genero_destinatario: 'mujer',
                edad_min: 30,
                edad_max: 80,
                permite_mensaje: true,
                permite_empaque: false,
            },
            {
                proveedor_id: missFlores.id,
                categoria_id: catFlores.id,
                nombre: 'Ramo de 6 rosas',
                descripcion: 'Ramo delicado de 6 rosas frescas, perfecto para ocasiones especiales',
                precio_base: 115.00,
                precio_venta: 115.00,
                stock: 10,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234722/Ramo_de_6_rosas_fwyzqg.webp',
                ocasiones: ['cumpleaños', 'aniversario'],
                personalidades: ['romántico', 'detallista'],
                genero_destinatario: 'mujer',
                edad_min: 15,
                edad_max: 70,
                permite_mensaje: true,
                permite_empaque: false,
            },
            {
                proveedor_id: missFlores.id,
                categoria_id: catFlores.id,
                nombre: 'Ramo de 18 Rosas',
                descripcion: 'Ramo de 18 rosas rojas frescas, ideal para demostrar amor',
                precio_base: 280.00,
                precio_venta: 280.00,
                stock: 5,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234723/Ramo_de_18_Rosas_nxewaq.webp',
                ocasiones: ['aniversario', 'san valentín'],
                personalidades: ['romántico', 'apasionado'],
                genero_destinatario: 'mujer',
                edad_min: 18,
                edad_max: 70,
                permite_mensaje: true,
                permite_empaque: false,
            },

            // ============= ARTE FLORAL =============
            {
                proveedor_id: arteFloral.id,
                categoria_id: catFlores.id,
                nombre: 'Arreglo de Flores y Rosas',
                descripcion: 'Arreglo floral premium combinando flores y rosas seleccionadas',
                precio_base: 980.00,
                precio_venta: 980.00,
                stock: 6,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234604/Arreglo_de_Flores_y_Rosas_ssjpca.jpg',
                ocasiones: ['aniversario', 'bodas'],
                personalidades: ['elegante', 'romántico'],
                genero_destinatario: 'mujer',
                edad_min: 20,
                edad_max: 80,
                permite_mensaje: true,
                permite_empaque: false,
            },
            {
                proveedor_id: arteFloral.id,
                categoria_id: catFlores.id,
                nombre: 'Arreglo en Caja',
                descripcion: 'Arreglo floral presentado en caja decorativa',
                precio_base: 260.00,
                precio_venta: 260.00,
                stock: 2,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234605/Arreglo_en_Caja_xtlssv.jpg',
                ocasiones: ['cumpleaños', 'agradecimiento'],
                personalidades: ['detallista', 'elegante'],
                genero_destinatario: 'mujer',
                edad_min: 18,
                edad_max: 70,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: arteFloral.id,
                categoria_id: catFlores.id,
                nombre: 'Ajá Primaveral',
                descripcion: 'Arreglo floral primaveral con flores de temporada',
                precio_base: 230.00,
                precio_venta: 230.00,
                stock: 16,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234603/Aj%C3%A1_Primaveral_ifutil.jpg',
                ocasiones: ['primavera', 'cumpleaños'],
                personalidades: ['alegre', 'colorido'],
                genero_destinatario: 'mujer',
                edad_min: 15,
                edad_max: 70,
                permite_mensaje: true,
                permite_empaque: false,
            },
            {
                proveedor_id: arteFloral.id,
                categoria_id: catFlores.id,
                nombre: 'Arreglo en Base Cuadrada + Chocolate',
                descripcion: 'Arreglo floral en base cuadrada, incluye chocolate',
                precio_base: 270.00,
                precio_venta: 270.00,
                stock: 20,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234604/Arreglo_en_Base_Cuadrada_Chocolate_zwxf27.jpg',
                ocasiones: ['cumpleaños', 'día de la madre'],
                personalidades: ['romántico', 'detallista'],
                genero_destinatario: 'mujer',
                edad_min: 18,
                edad_max: 70,
                permite_mensaje: true,
                permite_empaque: false,
            },
            {
                proveedor_id: arteFloral.id,
                categoria_id: catFlores.id,
                nombre: 'Arreglo de Girasoles',
                descripcion: 'Arreglo de girasoles frescos, alegre y vibrante',
                precio_base: 380.00,
                precio_venta: 380.00,
                stock: 10,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234604/Arreglo_de_Girasoles_vwwrdz.jpg',
                ocasiones: ['cumpleaños', 'motivación'],
                personalidades: ['alegre', 'optimista'],
                genero_destinatario: 'cualquiera',
                edad_min: 15,
                edad_max: 70,
                permite_mensaje: true,
                permite_empaque: false,
            },

            // ============= WONDER PERFUMES =============
            {
                proveedor_id: wonder.id,
                categoria_id: catPerfumes.id,
                nombre: 'Chocolate Addict EDP 100 ml',
                descripcion: 'Perfume con notas de chocolate, aroma dulce y cautivador',
                precio_base: 490.00,
                precio_venta: 490.00,
                stock: 5,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234788/Chocolate_Addict_EDP_100_ml_jo08vk.jpg',
                ocasiones: ['aniversario', 'san valentín'],
                personalidades: ['romántico', 'dulce'],
                genero_destinatario: 'mujer',
                edad_min: 18,
                edad_max: 50,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: wonder.id,
                categoria_id: catPerfumes.id,
                nombre: 'Mandarin Elixir',
                descripcion: 'Perfume con aroma cítrico y refrescante',
                precio_base: 650.00,
                precio_venta: 650.00,
                stock: 6,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234795/mandarin-elixir-2-768x768_mzesbh.jpg',
                ocasiones: ['cumpleaños', 'verano'],
                personalidades: ['refrescante', 'elegante'],
                genero_destinatario: 'cualquiera',
                edad_min: 18,
                edad_max: 55,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: wonder.id,
                categoria_id: catPerfumes.id,
                nombre: 'Hayaati Beau EDP 100 ml',
                descripcion: 'Perfume Hayaati Beau, fragancia duradera y sofisticada',
                precio_base: 320.00,
                precio_venta: 320.00,
                stock: 2,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234791/Hayaati_Beau_EDP_100_ml_rr6kzp.jpg',
                ocasiones: ['cumpleaños', 'graduación'],
                personalidades: ['elegante', 'sofisticado'],
                genero_destinatario: 'mujer',
                edad_min: 20,
                edad_max: 50,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: wonder.id,
                categoria_id: catPerfumes.id,
                nombre: 'Sensuous Night EDP 100 ml',
                descripcion: 'Perfume Sensuous Night, aroma nocturno y sensual',
                precio_base: 290.00,
                precio_venta: 290.00,
                stock: 16,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234943/Sensuous_Night_EDP_100_ml_pqyaul.jpg',
                ocasiones: ['cita', 'aniversario'],
                personalidades: ['sensual', 'misterioso'],
                genero_destinatario: 'mujer',
                edad_min: 21,
                edad_max: 55,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: wonder.id,
                categoria_id: catPerfumes.id,
                nombre: 'Yum Yum EDP 100 ml',
                descripcion: 'Perfume Yum Yum, aroma frutal y divertido',
                precio_base: 590.00,
                precio_venta: 590.00,
                stock: 20,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234943/Yum_Yum_EDP_100_ml_cphx7m.jpg',
                ocasiones: ['cumpleaños', 'día casual'],
                personalidades: ['divertido', 'juvenil'],
                genero_destinatario: 'mujer',
                edad_min: 16,
                edad_max: 40,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: wonder.id,
                categoria_id: catPerfumes.id,
                nombre: 'Fire On Ice EDP 110 ml',
                descripcion: 'Perfume Fire On Ice, combinación de fuego y hielo',
                precio_base: 490.00,
                precio_venta: 490.00,
                stock: 10,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234792/Fire_On_Ice_EDP_110_ml_hygpap.jpg',
                ocasiones: ['aniversario', 'san valentín'],
                personalidades: ['apasionado', 'elegante'],
                genero_destinatario: 'cualquiera',
                edad_min: 20,
                edad_max: 50,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: wonder.id,
                categoria_id: catPerfumes.id,
                nombre: 'Perla Sara EDP 100 ml',
                descripcion: 'Perfume Perla Sara, fragancia delicada y femenina',
                precio_base: 150.00,
                precio_venta: 150.00,
                stock: 5,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234936/Perla_Sara_EDP_100_ml_fqzpgu.jpg',
                ocasiones: ['cumpleaños', 'día de la madre'],
                personalidades: ['delicado', 'femenino'],
                genero_destinatario: 'mujer',
                edad_min: 18,
                edad_max: 65,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: wonder.id,
                categoria_id: catPerfumes.id,
                nombre: 'Surf Secret Code 100 ml',
                descripcion: 'Perfume Surf Secret Code, aroma fresco y marino',
                precio_base: 150.00,
                precio_venta: 150.00,
                stock: 6,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234794/Surf_Secret_Code_100_ml_lobsns.jpg',
                ocasiones: ['verano', 'cumpleaños'],
                personalidades: ['refrescante', 'aventurero'],
                genero_destinatario: 'hombre',
                edad_min: 18,
                edad_max: 45,
                permite_mensaje: true,
                permite_empaque: true,
            },
            {
                proveedor_id: wonder.id,
                categoria_id: catPerfumes.id,
                nombre: 'Dresscode For Her 85 ml',
                descripcion: 'Perfume Dresscode For Her, elegancia y sofisticación',
                precio_base: 150.00,
                precio_venta: 150.00,
                stock: 2,
                imagen_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777234789/Dresscode_For_Her_85_ml_fbd8oa.jpg',
                ocasiones: ['evento formal', 'aniversario'],
                personalidades: ['elegante', 'sofisticado'],
                genero_destinatario: 'mujer',
                edad_min: 22,
                edad_max: 55,
                permite_mensaje: true,
                permite_empaque: true,
            },
        ],
    })
}