import { PrismaClient } from '../../src/generated/prisma/client'

export async function seedProveedores(prisma: PrismaClient) {

    await prisma.proveedores.createMany({
        skipDuplicates: true,
        data: [
            {
                nombre_negocio: 'Artesanías Mamani',
                descripcion: 'Joyería artesanal hecha a mano en La Paz',
                email: 'mamani.artesanias@gmail.com',
                password_hash: '$2b$12$PLACEHOLDER_HASH',
                telefono: '71234567',
                direccion: 'Calle Sagárnaga #123, Zona Centro',
                rep_nombre: 'Juan Mamani',
                rep_telefono: '70011223',
                rep_email: 'juan.mamani@gmail.com',
                rep_anio_nacimiento: 1985,
                estado: 'aprobado',
                calificacion_prom: 4.8,
            },
            {
                nombre_negocio: 'Chocolates Quispe',
                descripcion: 'Chocolates y dulces artesanales bolivianos',
                email: 'chocolates.quispe@gmail.com',
                password_hash: '$2b$12$PLACEHOLDER_HASH',
                telefono: '76543210',
                direccion: 'Av. Buenos Aires #456, Zona Max Paredes',
                rep_nombre: 'María Quispe',
                rep_telefono: '79988776',
                rep_email: 'maria.quispe@gmail.com',
                rep_anio_nacimiento: 1990,
                estado: 'aprobado',
                calificacion_prom: 4.6,
            },
            {
                nombre_negocio: 'Flores Copacabana',
                descripcion: 'Arreglos florales y plantas decorativas',
                email: 'flores.copacabana@gmail.com',
                password_hash: '$2b$12$PLACEHOLDER_HASH',
                telefono: '79876543',
                direccion: 'Mercado Lanza, Piso 1, Sector Flores',
                rep_nombre: 'Carlos Flores',
                rep_telefono: '76655443',
                rep_email: 'carlos.flores@gmail.com',
                rep_anio_nacimiento: 1982,
                estado: 'aprobado',
                calificacion_prom: 4.5,
            },
            {
                nombre_negocio: 'TechGadgets Bolivia',
                descripcion: 'Accesorios tecnológicos personalizados',
                email: 'techgadgets.bo@gmail.com',
                password_hash: '$2b$12$PLACEHOLDER_HASH',
                telefono: '72345678',
                direccion: 'Av. 6 de Agosto #789, Zona Sopocachi',
                rep_nombre: 'Ana Rojas',
                rep_telefono: '71122334',
                rep_email: 'ana.rojas@techgadgets.bo',
                rep_anio_nacimiento: 1995,
                estado: 'aprobado',
                calificacion_prom: 4.3,
            },
        ],
    })
}
