import { PrismaClient } from '../../src/generated/prisma/client'

export async function seedProveedores(prisma: PrismaClient) {

    await prisma.proveedores.createMany({
        skipDuplicates: true,
        data: [
            {
                nombre_negocio: 'Miniso Bolivia',
                descripcion: 'Tienda de productos de estilo de vida, artículos de regalo, peluches, tecnología y accesorios',
                logo_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777321840/MINIS_rkkhfg.jpg',
                email: 'miniso.bolivia@gmail.com',
                password_hash: '$2b$12$PLACEHOLDER_HASH_MINISO',
                telefono: '76543210',
                direccion: 'Av. Arce #2750, Zona San Jorge, La Paz',
                rep_nombre: 'Carlos Mendoza',
                rep_telefono: '71223344',
                rep_email: 'carlos.mendoza@miniso.bo',
                rep_anio_nacimiento: 1988,
                estado: 'aprobado',
                calificacion_prom: 4.7,
            },
            {
                nombre_negocio: 'Giftland Bolivia',
                logo_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777321841/313424317_491968809634570_7433880416632053513_n_zqyex5.jpg',
                descripcion: 'Tienda de regalos, peluches temáticos, juguetes y cajas sorpresa',
                email: 'giftland.bolivia@gmail.com',
                password_hash: '$2b$12$PLACEHOLDER_HASH_GIFTLAND',
                telefono: '77889900',
                direccion: 'Av. Busch #1560, Zona Miraflores, La Paz',
                rep_nombre: 'Patricia Vargas',
                rep_telefono: '70099887',
                rep_email: 'patricia.vargas@giftland.bo',
                rep_anio_nacimiento: 1992,
                estado: 'aprobado',
                calificacion_prom: 4.5,
            },
            {
                nombre_negocio: 'Miss Flores',
                logo_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777321840/missflores_g7y4tn.webp',
                descripcion: 'Arreglos florales, ramos y decoraciones para ocasiones especiales',
                email: 'missflores.lapaz@gmail.com',
                password_hash: '$2b$12$PLACEHOLDER_HASH_MISSFLORES',
                telefono: '75554321',
                direccion: 'Calle Loayza #345, Zona Casco Viejo, La Paz',
                rep_nombre: 'Laura Fernández',
                rep_telefono: '71133445',
                rep_email: 'laura.fernandez@missflores.bo',
                rep_anio_nacimiento: 1985,
                estado: 'aprobado',
                calificacion_prom: 4.9,
            },
            {
                nombre_negocio: 'Arte Floral Bolivia',
                logo_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777321841/arte_kzijh5.png',
                descripcion: 'Arreglos florales, ramos personalizados y decoración con flores',
                email: 'artefloral.bolivia@gmail.com',
                password_hash: '$2b$12$PLACEHOLDER_HASH_ARTEFLORAL',
                telefono: '76655443',
                direccion: 'Av. 20 de Octubre #789, Zona Sopocachi, La Paz',
                rep_nombre: 'Roberto Terán',
                rep_telefono: '72233446',
                rep_email: 'roberto.teran@artefloral.bo',
                rep_anio_nacimiento: 1980,
                estado: 'aprobado',
                calificacion_prom: 4.6,
            },
            {
                nombre_negocio: 'Wonder Perfumes Bolivia',
                descripcion: 'Perfumes y fragancias importadas de alta calidad',
                logo_url: 'https://res.cloudinary.com/dcq7xfyyn/image/upload/v1777321840/wonderimg_quqgak.gif',
                email: 'wonder.perfumes@gmail.com',
                password_hash: '$2b$12$PLACEHOLDER_HASH_WONDER',
                telefono: '77778899',
                direccion: 'Av. 16 de Julio #456, Zona Sopocachi, La Paz',
                rep_nombre: 'Daniela Ríos',
                rep_telefono: '70011234',
                rep_email: 'daniela.rios@wonder.bo',
                rep_anio_nacimiento: 1990,
                estado: 'aprobado',
                calificacion_prom: 4.4,
            },
        ],
    })
}