export const C = {
  bordeaux: "#5A0F24",
  garnet:   "#8E1B3A",
  crimson:  "#AB3A50",
  gold:     "#BC9968",
  choco:    "#5C3A2E",
  beige:    "#FAF5EE",
  cream:    "#FFF8F1",
  white:    "#FFFFFF",
  gray:     "#8A7A73",
};

export const COLORS = C;

export const PRODUCTS = [
  {
    id:1,
    image:"https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=300&fit=crop&q=80",
    name:"Caja Cata Ciega Premium",
    desc:"4 vinos reserva tarijeños con guía de maridaje y copa de cristal incluida.",
    price:"Bs.280", old:"Bs.320",
    tag:"⭐ MÁS VENDIDO", tagC:"#8E1B3A",
    bg:"#FEF0F3", cat:"vinos",
    ocasiones:["cumpleaños","aniversario","agradecimiento"],
    rating:"4.9", rev:"142", brand:"Viñedos Tarijeños",
  },
  {
    id:2,
    image:"https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=400&h=300&fit=crop&q=80",
    name:"Trufas Cacao Amazónico",
    desc:"12 trufas rellenas de frutos exóticos bolivianos. Sin preservantes artificiales.",
    price:"Bs.120", old:null,
    tag:"✨ NUEVO", tagC:"#7A4F1A",
    bg:"#FDF7EE", cat:"chocolates",
    ocasiones:["cumpleaños","san valentin","agradecimiento","amistad"],
    rating:"4.9", rev:"89", brand:"Chocobeni",
  },
  {
    id:3,
    image:"https://images.unsplash.com/photo-1608181831718-c9fc5b1cac8c?w=400&h=300&fit=crop&q=80",
    name:"Set Velas Relajación",
    desc:"Cera de abeja pura con esencias naturales de los valles paceños.",
    price:"Bs.180", old:null,
    tag:"🤲 ARTESANAL", tagC:"#5C3A2E",
    bg:"#F4EEE8", cat:"spa",
    ocasiones:["cumpleaños","agradecimiento","amistad","sin-ocasion"],
    rating:"4.8", rev:"67", brand:"Aromasol",
  },
  {
    id:4,
    image:"https://images.unsplash.com/photo-1607344645866-009c320b63e0?w=400&h=300&fit=crop&q=80",
    name:"Canasta Andina Deluxe",
    desc:"8 productos gourmet artesanales con empaque premium y tarjeta dedicatoria.",
    price:"Bs.450", old:"Bs.500",
    tag:"💎 EXCLUSIVO", tagC:"#5A0F24",
    bg:"#F5EAEB", cat:"canastas",
    ocasiones:["cumpleaños","aniversario","navidad","agradecimiento"],
    rating:"5.0", rev:"203", brand:"Sabores del Ande",
  },
  {
    id:5,
    image:"https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop&q=80",
    name:"Box Sorpresa Personalizado",
    desc:"Arma tu caja ideal. Tú eliges los productos y nosotros lo empacamos con amor.",
    price:"Bs.220", old:null,
    tag:"🎯 POPULAR", tagC:"#185FA5",
    bg:"#EEF4FB", cat:"personalizados",
    ocasiones:["cumpleaños","aniversario","san valentin","amistad","navidad"],
    rating:"4.9", rev:"118", brand:"Emotia Originals",
  },
  {
    id:6,
    image:"https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=400&h=300&fit=crop&q=80",
    name:"Kit Ritual Spa en Casa",
    desc:"Sales de baño, aceites y mascarillas 100% naturales de los Yungas bolivianos.",
    price:"Bs.260", old:null,
    tag:"🌱 ORGÁNICO", tagC:"#3B6D11",
    bg:"#EDF5EE", cat:"spa",
    ocasiones:["cumpleaños","agradecimiento","sin-ocasion","amistad"],
    rating:"4.8", rev:"55", brand:"Tierra Viva",
  },
  {
    id:7,
    image:"https://images.unsplash.com/photo-1547586696-ea22b4d4235d?w=400&h=300&fit=crop&q=80",
    name:"Singani Reserva Vintage",
    desc:"Botella edición especial con caja de madera grabada y copa de cristal incluida.",
    price:"Bs.320", old:null,
    tag:"🏆 EDICIÓN LTD", tagC:"#534AB7",
    bg:"#F3EBF4", cat:"vinos",
    ocasiones:["aniversario","navidad","agradecimiento","cumpleaños"],
    rating:"4.8", rev:"41", brand:"Casa Real",
  },
  {
    id:8,
    image:"https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400&h=300&fit=crop&q=80",
    name:"Mieles & Mermeladas Gourmet",
    desc:"Set de 3 mieles artesanales y 2 mermeladas de los valles de Cochabamba.",
    price:"Bs.95", old:null,
    tag:"🌸 NATURAL", tagC:"#854F0B",
    bg:"#FEF5E4", cat:"chocolates",
    ocasiones:["agradecimiento","amistad","sin-ocasion","navidad"],
    rating:"4.7", rev:"76", brand:"Abejas del Valle",
  },

  // ══════════════════════════════════════════════
  // JUGUETES — para niños y adultos
  // ══════════════════════════════════════════════
  {
    id:9,
    image:"https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=300&fit=crop&q=80",
    name:"Peluche Llama Andina",
    desc:"Tierno peluche de llama artesanal hecho a mano en Bolivia. Ideal para todas las edades.",
    price:"Bs.85", old:null,
    tag:"🧸 ARTESANAL", tagC:"#7A4F1A",
    bg:"#FEF9F0", cat:"juguetes",
    ocasiones:["cumpleaños","navidad","amistad","sin-ocasion"],
    rating:"4.9", rev:"94", brand:"Manualidades del Altiplano",
  },
  {
    id:10,
    image:"https://images.unsplash.com/photo-1611996575749-79a3a250f948?w=400&h=300&fit=crop&q=80",
    name:"Juego de Mesa Familiar",
    desc:"Pack de 3 juegos clásicos reimaginados. Perfecto para noches en familia o con amigos.",
    price:"Bs.160", old:"Bs.195",
    tag:"🎲 FAVORITO", tagC:"#185FA5",
    bg:"#EEF4FB", cat:"juguetes",
    ocasiones:["cumpleaños","navidad","amistad","sin-ocasion"],
    rating:"4.8", rev:"73", brand:"Lúdico Bolivia",
  },
  {
    id:11,
    image:"https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=400&h=300&fit=crop&q=80",
    name:"Set Creativo Acuarelas",
    desc:"Kit completo de acuarelas profesionales + lienzos + pinceles para artistas en ciernes.",
    price:"Bs.130", old:null,
    tag:"🎨 CREATIVO", tagC:"#8E1B3A",
    bg:"#FFF0F8", cat:"juguetes",
    ocasiones:["cumpleaños","navidad","amistad","sin-ocasion"],
    rating:"4.9", rev:"61", brand:"Arte Vivo",
  },
  {
    id:12,
    image:"https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&h=300&fit=crop&q=80",
    name:"Muñeca Cholita Artesanal",
    desc:"Muñeca vestida con traje tradicional paceño, hecha a mano por artesanas locales.",
    price:"Bs.110", old:null,
    tag:"🏆 ÚNICO", tagC:"#5A0F24",
    bg:"#F5EAEB", cat:"juguetes",
    ocasiones:["cumpleaños","navidad","agradecimiento","sin-ocasion"],
    rating:"5.0", rev:"48", brand:"Artesanas de La Paz",
  },
  {
    id:13,
    image:"https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop&q=80",
    name:"Puzzle Mapa Bolivia 500 pzs",
    desc:"Rompecabezas artesanal del mapa de Bolivia con detalles de flora y fauna nacional.",
    price:"Bs.145", old:null,
    tag:"🧩 EDUCATIVO", tagC:"#3B6D11",
    bg:"#EDF5EE", cat:"juguetes",
    ocasiones:["cumpleaños","navidad","sin-ocasion","agradecimiento"],
    rating:"4.7", rev:"37", brand:"Juega Bolivia",
  },
  {
    id:14,
    image:"https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=400&h=300&fit=crop&q=80",
    name:"Kit Manualidades Niños",
    desc:"Todo para crear: plastilina vegetal, stickers, papel de colores y guía de proyectos.",
    price:"Bs.75", old:null,
    tag:"✂️ DIVERTIDO", tagC:"#7A4F1A",
    bg:"#FEF9F0", cat:"juguetes",
    ocasiones:["cumpleaños","navidad","sin-ocasion"],
    rating:"4.8", rev:"82", brand:"Manitos Creativas",
  },
];

export const CATS = [
  { id:"todos",          label:"Todos",           emoji:"🎁" },
  { id:"vinos",          label:"Vinos & Licores",  emoji:"🍷" },
  { id:"chocolates",     label:"Chocolates",       emoji:"🍫" },
  { id:"canastas",       label:"Canastas",         emoji:"🧺" },
  { id:"spa",            label:"Vales & Experiencias", emoji:"🎟️" },
  { id:"juguetes",       label:"Juguetes",         emoji:"🧸" },
  { id:"personalizados", label:"Personalizados",   emoji:"✨" },
];

export const OCASIONES = [
  { id:"todas",          label:"Cualquier ocasión", emoji:"🎊" },
  { id:"cumpleaños",     label:"Cumpleaños",         emoji:"🎂" },
  { id:"aniversario",    label:"Aniversario",        emoji:"💑" },
  { id:"san valentin",   label:"San Valentín",       emoji:"❤️" },
  { id:"navidad",        label:"Navidad",            emoji:"🎄" },
  { id:"agradecimiento", label:"Agradecimiento",     emoji:"🙏" },
  { id:"amistad",        label:"Amistad",            emoji:"🤝" },
  { id:"sin-ocasion",    label:"Sin ocasión",        emoji:"😊" },
];

export const TESTIMONIALS = [
  { text:"Encontré el regalo perfecto para mi mamá en 5 minutos. ¡Lloró de alegría!", name:"Valentina C.", role:"La Paz", avatar:"V" },
  { text:"Llevaba semanas sin idea para el cumpleaños de mi novio. Emotia lo resolvió.", name:"Sofía M.", role:"La Paz", avatar:"S" },
  { text:"Lo uso para todos mis clientes corporativos. Las recomendaciones son increíblemente precisas.", name:"Carlos R.", role:"La Paz", avatar:"C" },
];
